Modify `build.gradle` to add `discovery-client` dependency.

[source,groovy]
.bookrecommendation/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookrecommendation/build.gradle[tag=discoveryclient]
}
----

Also, append to `bookrecommendation`.`application.yml` the following snippet:

[source,yaml]
.bookrecommendation/src/main/resources/application.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application.yml[tag=consul]
----

Modify `BookInventoryClient` and `BookCatalogueClient` to use the service id instead of a harcoded ip.

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt[tag=consul]
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt[tag=clazz]
----

<1> Use the configuration value `micronaut.application.name` used in `bookcatalogue` as service `id`.

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt[tag=consul]
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt[tag=clazz]
----

<1> Use the configuration value `micronaut.application.name` used in `bookinventory` as service `id`.

Disable consul registration in tests:

[source,yaml]
.bookrecommendation/src/main/resources/application-test.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application-test.yml[tag=consul]
----