Create the `bookrecommendation` microservice:

`mn create-app --lang kotlin example.micronaut.bookrecommendation.bookrecommendation`

The previous command creates a folder named `bookrecommendation` and a Micronaut app inside it with
default package: `example.micronaut.bookrecommendation`.

Create an interface to map operations with `bookcatalogue` and a Micronaut Declarative HTTP Client to consume it.

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueOperations.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueOperations.kt[]
----

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt[tag=harcoded]
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookCatalogueClient.kt[tag=clazz]
----

<1> Use `@Client` to use https://docs.micronaut.io/latest/guide/index.html#clientAnnotation[declarative HTTP Clients]

The client returns a data class. Create it in the `bookrecommendation`:
[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/Book.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/Book.kt[]
----

Create an interface to map operations with `bookinventory` and a Micronaut Declarative HTTP Client to consume it.

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryOperations.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryOperations.kt[]
----

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt[tag=harcoded]
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookInventoryClient.kt[tag=clazz]
----

<1> Use `@Client` to use https://docs.micronaut.io/latest/guide/index.html#clientAnnotation[declarative HTTP Clients]

Create a Controller which injects both clients.

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BooksController.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BooksController.kt[]
----

<1> The class is defined as a controller with the http://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/books`
<2> Constructor injection
<3> The `@Get` annotation is used to map the index method to `/books` requests that use an HTTP GET.

The previous controller returns a `Flowable<BookRecommendation>`. Create the `BookRecommendation` data class:

[source,kotlin]
.bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookRecommendation.kt
----
include::{sourceDir}/bookrecommendation/src/main/kotlin/example/micronaut/bookrecommendation/BookRecommendation.kt[]
----

`BookCatalogueClient` and `BookInventoryClient` will fail to consume the `bookcatalogue` and `bookinventory` during the tests phase.

Using the https://docs.micronaut.io/latest/guide/index.html#clientFallback[@Fallback] annotation you can declare a fallback implementation of a client that will be picked up and used once all possible retries have been exhausted

Create `@Fallback` alternatives in the `test` classpath.

[source,kotlin]
.bookrecommendation/src/test/kotlin/example/micronaut/bookrecommendation/BookInventoryClientStub.kt
----
include::{sourceDir}/bookrecommendation/src/test/kotlin/example/micronaut/bookrecommendation/BookInventoryClientStub.kt[]
----

[source,kotlin]
.bookrecommendation/src/test/kotlin/example/micronaut/bookrecommendation/BookCatalogueClientStub.kt
----
include::{sourceDir}/bookrecommendation/src/test/kotlin/example/micronaut/bookrecommendation/BookCatalogueClientStub.kt[]
----

Write a test:

[source,kotlin]
.bookrecommendation/src/test/kotlin/example/micronaut/bookrecommendation/BooksControllerSpec.kt
----
include::{sourceDir}/bookrecommendation/src/test/kotlin/example/micronaut/bookrecommendation/BooksControllerSpec.kt[]
----

Edit `application.yml`

[source,yaml]
.bookrecommendation/src/main/resources/application.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application.yml[tag=mn]
----

<1> Configure the application name. The app name will be used later in the tutorial.
<2> Configure the app to listen at port 8080

Create a file named `application-test.yml` which is used in the test environment:

[source,yaml]
.bookrecommendation/src/main/resources/application-test.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application-test.yml[tag=port]
----

<1> Start the micronaut microservice at a random port when running the tests.